### ISSUE TITLE
Content Security Policy error during login

### ISSUE THREAD

**Issue by Cerfoglg** [soudis/discoursesso#12]
After setting up the app on the latest version of Nextcloud and configuring Discourse to use SSO with it, attempting to log in from Discourse will redirect to the Nextcloud login, however after submitting the form it fails to redirect. The frontend reports the error:

    Refused to send form data to <DISCOURSE_URL> because it violates the following Content 
    Security Policy directive: "form-action 'self'".

However the user is successfully logged into Discourse upon refreshing the page. Do you know why this error is occuring? This happens both on two production instances of Nextcloud and Discourse we set up, and locally on my machine whilst testing (using Docker for deployment).

**Comment by soudis** [comment]
It is not advised to open discourse inside an iframe in nextcloud, because this leads to a lot of problems with different browser (due to security restrictions such as this). So if you add the external app url to the menu, make sure to tell nextlcoud to open it in a separate tab.

If you still want to use an iframe, you can try to fork an modify this plugin: https://github.com/soudis/discourse-allow-same-origin (it's fairy simple, you just have to set habidatcloudurl to the URL of your cloud instance in the plugin.rb file)

**Comment by Cerfoglg** [comment]
@soudis The issue I'm having is that when the user goes to Discourse they get redirected to NextCloud, and when they try to log in there what I assumed would happen is that they get redirected back to Discourse, now logged in. But instead it hangs due to that error. If the user goes to Nextcloud directly and logs in there, then they log into Nextcloud no problem, and can go to Discourse where they are now logged in there correctly, but we are looking to have the users land on the Discourse page first, so they will most likely log in from there.

**Comment by chicco785** [comment]
The issue is related to lack of policies for the FormAction. We have a PR for that, and will submit it shortly

**Comment by chicco785** [comment]
For your information, also, issue is easily reproducible with base configuration of nextcloud + discourse.

See our compose used to test:
```
version: '2'
services:
  nextcloud:
    image: 'nextcloud:18.0.3-apache'
    networks:
      - test
    ports:
      - '8080:80'
    volumes:
      - $PWD/custom_apps/discoursesso:/var/www/html/custom_apps/discoursesso
      - $PWD/config:/var/www/html/config
  postgresql:
    image: 'bitnami/postgresql:11'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - test
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
  redis:
    image: 'bitnami/redis:5.0'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - test
    volumes:
      - 'redis_data:/bitnami'
  discourse:
    image: 'bitnami/discourse:2'
    ports:
      - '80:3000'
    depends_on:
      - postgresql
      - redis
    volumes:
      - 'discourse_data:/bitnami'
    networks:
      - test
    environment:
      - POSTGRESQL_HOST=postgresql
      - POSTGRESQL_ROOT_USER=postgres
      - POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=bitnami_application
      - POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME=bn_discourse
      - POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD=bitnami1
      - DISCOURSE_POSTGRESQL_NAME=bitnami_application
      - DISCOURSE_POSTGRESQL_USERNAME=bn_discourse
      - DISCOURSE_POSTGRESQL_PASSWORD=bitnami1
      - DISCOURSE_HOSTNAME=www.example.com
  sidekiq:
    image: 'bitnami/discourse:2'
    depends_on:
      - discourse
    volumes:
      - 'sidekiq_data:/bitnami'
    command: 'nami start --foreground discourse-sidekiq'
    networks:
      - test
    environment:
      - DISCOURSE_POSTGRESQL_NAME=bitnami_application
      - DISCOURSE_POSTGRESQL_USERNAME=bn_discourse
      - DISCOURSE_POSTGRESQL_PASSWORD=bitnami1
      - DISCOURSE_HOST=discourse
      - DISCOURSE_PORT=3000
      - DISCOURSE_HOSTNAME=www.example.com
volumes:
  postgresql_data:
    driver: local
  redis_data:
    driver: local
  discourse_data:
    driver: local
  sidekiq_data:
    driver: local
networks:
  test:
``` 

1. download in custom_apps the discoursesso plugin: https://github.com/soudis/discoursesso/releases

1. configure `www.example.com` in your /etc/hosts

1. run `docker-compose up -d`

1. Default username and password for discourse are user e bitnami123

1. login in container and run make in the plugin folder

1. configure sso
